# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image:  postgis/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB : task-manager
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080